#pragma once
// Array
class AddArrayToDictionaryCommand;
class AddItemToArrayAtCommand;
class AddLengthToArrayCommand;
class GetItemFromArrayCommand;

// Functions
class ShowFunctionCommand;
class ShowUpFunctionCommand;
class RandomFunctionCommand;
class GetAllFilesInDirectoryCommand;
class GetFilesInDirectoryByExtensionCommand;
class GetAudioFilesInDirectoryCommand;
class GetVideoFilesInDirectoryCommand;
class RenameFileCommand;
class RemoveFileCommand;
class RemoveFilesCommand;
class RemoveDirectoryCommand;
class CountCommand;
class GetFileExtensionCommand;
class MoveFileCommand;
class MoveFilesCommand;
class CopyFileCommand;
class CopyFilesCommand;
class GetDownCommand;
class ParseIntCommand;

// Miscellaneous
class ConstantToReturnValueCommand;
class GetFromValueCommand;
class IdentifierToReturnValueCommand;

// Operators
class DivideCommand;
class EqualsCommand;
class EqualsToCommand;
class GreaterEqualsToCommand;
class GreaterThanCommand;
class MinusCommand;
class MinusMinusCommand;
class ModuloCommand;
class NotEqualsToCommand;
class PlusCommand;
class PlusPlusCommand;
class SmallerEqualsToCommand;
class SmallerThanCommand;
class TimesCommand;
class OrCommand;
class AndCommand;