#pragma once

enum IToken
{
	NONE = 0,
	NEWLINE,
	PLUS,
	MINUS,
	TIMES,
	DIVIDE,
	LESS_THAN,
	LARGER_THAN,
	IDENTIFIER, // VARB **i**
	NUMBER, // 1-2-3-4
	TEXT, // "txt" 
	FACT,
	TYPE_NUMBER,
	TYPE_TEXT,
	TYPE_FACT,
	CONDITION_OPEN,  // ( -> simuleren?
	CONDITION_CLOSE, // ) -> simuleren?
	FUNCTION_OPEN,  // ( -> simuleren?
	FUNCTION_CLOSE, // ) -> simuleren?
	BODY_OPEN, // ____
	BODY_CLOSED,// ____
	DO,
	WHILE,
	IF,
	ELSE,
	ELIF,
	EQUALS, // IS
	EQUALS_TO, // LIKE
	AND_PARA, // , (comma)
	CLASS,
	BOOL,
	MODULO,
	PRIVATE,
	FOR,
	FOREACH,
	PRINT, // TODO: mag weg nu?
	PRINTUP, // TODO: mag weg nu?
	PLUSPLUS,
	MINUSMINUS,
	SEPARATOR,
	DECLARATION,
	IN,
	FUNCTION_CALL,
	FUNCTION_DECLARE,
	NAMESPACE,
	COMMENT,
	ASSIGNMENT,
	RETURNVALUE,
	START_PARAMETERS,
	FUNCTION_DECLARE_OPEN,
	FUNCTION_DECLARE_CLOSE,
	FUNCTIONUSE,
	COMINGPARAMETER,
	ARRAY_OPEN,
	ARRAY_CLOSE,
	SWITCH_CASE,
	SWITCH_DEFAULT,
	SWITCH,
	ANY // ALS LAATSTE ! (?)
};